/*Modelagem - AutoRelacionamento*/
USE test;

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    HORAS INT, 
    VALOR FLOAT(10,2),
    ID_PREREQ INT
);
/*utilizar para organização*/
INSERT INTO CURSOS VALUES (1,'SEM PRE REQ',0,0.0,NULL);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES (NULL,'BD REALACIONAL',40,200.0,NULL);
INSERT INTO CURSOS VALUES (NULL,'BUSINESS INTELLIGENCE',40,800.0,1);
INSERT INTO CURSOS VALUES (NULL,'RELATORIOS AVANCADOS',20,600.0,2);
INSERT INTO CURSOS VALUES (NULL,'LÓGICA DE PROGRAMAÇÃO',20,300.0,NULL);
INSERT INTO CURSOS VALUES (NULL,'RUBY',40,700.0,4);

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ,'SEM_REQ')
FROM CURSOS;

SELECT NOME, VALOR, HORAS , IFNULL(ID_PREREQ,'SEM_REQ')
FROM CURSOS;

/*INFORME O NOME, VALOR, HORAS E O NOME DO PRE REQUISITO DO CURSO*/

SELECT C.NOME,C.VALOR,C.HORAS, IFNULL(A.NOME,'SEM PRE REQ') AS PRE_REQUISITO
FROM CURSOS C
LEFT JOIN CURSOS A
ON C.ID_PREREQ = A.IDCURSO;