CREATE DATABASE Cursores;
USE Cursores;

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL, 'MAFRA',32423,23213,12234);
INSERT INTO VENDEDORES VALUES(NULL, 'JOSE',65161,66541,2135);
INSERT INTO VENDEDORES VALUES(NULL, 'CLARA',98446,65464,2165);
INSERT INTO VENDEDORES VALUES(NULL, 'PEDRO',5641,65486,65846);
INSERT INTO VENDEDORES VALUES(NULL, 'LUIS',32423,23213,98746);
INSERT INTO VENDEDORES VALUES(NULL, 'CARLOS',74654,35435,54774);
INSERT INTO VENDEDORES VALUES(NULL, 'MONICA',51636,64586,90000);
INSERT INTO VENDEDORES VALUES(NULL, 'GABRIEL',46545,687475,843545);


SELECT * FROM VENDEDORES;

+------------+---------+-------+--------+--------+
| IDVENDEDOR | NOME    | JAN   | FEV    | MAR    |
+------------+---------+-------+--------+--------+
|          1 | MAFRA   | 32423 |  23213 |  12234 |
|          2 | JOSE    | 65161 |  66541 |   2135 |
|          3 | CLARA   | 98446 |  65464 |   2165 |
|          4 | PEDRO   |  5641 |  65486 |  65846 |
|          5 | LUIS    | 32423 |  23213 |  98746 |
|          6 | CARLOS  | 74654 |  35435 |  54774 |
|          7 | MONICA  | 51636 |  64586 |  90000 |
|          8 | GABRIEL | 46545 | 687475 | 843545 |
+------------+---------+-------+--------+--------+

/*Vendas por vendedor*/
SELECT NOME, (JAN + FEV +MAR) AS TOTAL
FROM VENDEDORES;

/*Media dos vendedores*/
SELECT NOME, TRUNCATE((JAN + FEV +MAR)/3,2) AS MEDIA_TOTAL
FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL FLOAT,
    MEDIA FLOAT
);



/*CURSORES = UMA PROGRAMAÇÃO DENTRO DE PROCEDURES
O que faz então um cursor? Um cursor executa uma certa query e permite ao programa ler o resultado registo a registo (sequencialmente) num ciclo, eventualmente fazendo múltiplas operações com cada registo.
CASOS - VARRER TABELA PARA FAZER UMA PROGRAMAÇÃO MAIS COMPLICADA
OU QUANDO NÃO CONSEQUE SE RESOLVER COM UMA PROCEDURE OU QUERY MAIS ELABORADA.
*** São carregados na memória ram e por isso podem levar a um
mau desempenho
*** NÃO UTILIZE O MESMO NOME DAS COLUNAS PODE DAR AMBIGUIDADE
*/
DELIMITER $
CREATE PROCEDURE INSEREDADOS()
BEGIN
        DECLARE FIM INT DEFAULT 0;
        DECLARE MES1,MES2, MES3, TOTAL INT;
        DECLARE MEDIA FLOAT;
        DECLARE VNOME VARCHAR(50);

        DECLARE REGISTRO CURSOR FOR(
            SELECT NOME,JAN,FEV,MAR FROM VENDEDORES
        );

        DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

        OPEN REGISTRO;

        REPEAT 

            FETCH REGISTRO INTO VNOME,MES1,MES2,MES3;
            IF NOT FIM THEN
                SET TOTAL = (MES1 + MES2 + MES3);
                SET MEDIA = (TOTAL/3);

                INSERT INTO VEND_TOTAL VALUES(VNOME, MES1,MES2,MES3,TOTAL,MEDIA);
            END IF;
        UNTIL FIM END REPEAT;

        CLOSE REGISTRO;
END
$

DELIMITER ;

SELECT * FROM VENDEDORES;
SELECT * FROM VEND_TOTAL;

CALL INSEREDADOS();

SELECT * FROM VEND_TOTAL;