/*  Requisitos

    Carros entram para realizar serviços e os seus respectivos donos.
    Cada cliente possui apenas um carro
    Carro possui uma marca
    Cores dos carros para ter idéia de qual tinta comprar
    Carro pode ter mais de uma cor
    Necessita armazenar telefones dos clientes
    mas não são obrigatórios;

    Inicio da Modelagem

    Cliente -> Carro
    Cliente -> Telefone
    Carro ->  Marca
    Carro ->  mais de uma cor
    
*/


CREATE DATABASE PROJETOOFICINA;
USE PROJETOOFICINA;

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(35) NOT NULL,
    CPF VARCHAR(11) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    SEXO ENUM('M','F'),
    ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO VARCHAR(11) NOT NULL,
    TIPO ENUM('COM','RES','CEL') NOT NULL,
    ID_CLIENTE INT
);

CREATE TABLE CARRO(
    IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(30) NOT NULL,
    ANO DATETIME NOT NULL,
    CHASSI VARCHAR(30) NOT NULL,
    ID_MARCA INT 
);

CREATE TABLE MARCA(
    IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) UNIQUE
);

CREATE TABLE COR(
    IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    COR VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CARRO_COR(
    ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY(ID_CARRO,ID_COR)
);

/*CONSTRAINT*/
/*FK_DA ONDE QUE PERTENCE_TABELA DE ONDE VENHO*/
ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO 
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO)
REFERENCES CARRO(IDCARRO);

/* PREENCHER O BANCO COM NO MINIMO 10 CLIENTE */

INSERT INTO CARRO() VALUES();